import time
# from ImageProcessing.OpenCamera import startVideo
from DroneCode.Drone import Drone

drone = Drone()
drone.vehicle_info()
time.sleep(3)
drone.arm()
time.sleep(3)
drone.set_speed(150, 250)
time.sleep(1)
drone.simple_takeoff(10)
time.sleep(5)
print(drone.get_location())
time.sleep(1)
# drone.Upload_mission("deneme.txt")
# time.sleep(2)
# drone.Change_mode("AUTO")
# time.sleep(30)
drone.change_mode("GUIDED")
time.sleep(1)
print("Birinci ileri")
drone.change_velocity(0.5, 0, 0)
time.sleep(10)
print("İkinci geri")
drone.change_velocity(-0.5, 0, 0)
time.sleep(10)
print("Üçüncü sağa")
drone.change_velocity(0, 0.5, 0)
time.sleep(10)
print("Dördüncü sola")
drone.change_velocity(0, -0.5, 0)
time.sleep(10)
drone.change_mode("LAND")
time.sleep(10)
drone.close_vehicle()
